export type Project = {
  slug: string;
  title: string;
  summary: string;
  description: string;
  stack: string[];
  features: string[];
  problem: string;
  approach: string;
  impact: string;
  live: string;
  thumbnail: string;
};

export const projects: Project[] = [
  {
    slug: "peoplescreed-ai",
    title: "Peoplescreed.AI",
    summary: "An integrated HR platform for recruitment, onboarding, performance, SSO administration, and workforce analytics.",
    description: "Peoplescreed.AI brings core HR workflows into one responsive product experience, helping teams manage people operations from hiring through performance reporting.",
    stack: ["React.js", "Next.js", "TypeScript", "RTK Query", "Redux Thunk", "MUI", "ApexCharts"],
    features: ["Recruitment, onboarding, and performance modules", "Central SSO administration", "Interactive analytics dashboards", "SSR, SSG, and ISR-ready rendering patterns", "Responsive cross-browser interfaces"],
    problem: "HR teams needed one place to manage hiring, onboarding, access, and performance without jumping between disconnected tools.",
    approach: "Built a scalable Next.js frontend with reusable MUI components, optimized rendering, and RTK Query-powered data flows for predictable server communication.",
    impact: "Reduced manual HR effort and made performance and people analytics easier to read, share, and act on.",
    live: "https://peoplescreed.ai/",
    thumbnail: "/performance.jpg",
  },
  {
    slug: "identity-gram",
    title: "Identity Gram",
    summary: "A secure identity verification platform covering KYC, KYB, AML, biometric checks, and compliance reporting.",
    description: "Identity Gram helps businesses verify people and organizations through digital identity flows, biometric signals, and compliance-focused reporting.",
    stack: ["React.js", "Next.js", "TypeScript", "Redux Toolkit", "RTK Query", "MUI", "Recharts"],
    features: ["KYC, KYB, and AML verification flows", "Facial and biometric identity checks", "Right-to-work and pre-employment screening", "Reference and social validation tools", "Geolocation-aware customer monitoring", "SMS signature verification"],
    problem: "Businesses needed a faster and safer way to verify identities while reducing fraud and meeting regulatory requirements.",
    approach: "Designed real-time verification journeys, structured compliance dashboards, and reusable UI modules for high-volume identity checks.",
    impact: "Improved digital trust with quicker checks, clearer reporting, and a smoother verification experience for end users.",
    live: "https://identitygram.co.uk/",
    thumbnail: "/identity-gram.jpg",
  },
  {
    slug: "agentic-creed",
    title: "Agentic Creed",
    summary: "A unified business platform for loyalty, sales, service, operations, marketing, and customer support.",
    description: "Agentic Creed connects customer-facing teams with a single operational layer for customer experience, loyalty, call-center support, and growth workflows.",
    stack: ["React.js", "Next.js", "TypeScript", "Redux Toolkit", "RTK Query", "MUI", "AWS", "Recharts"],
    features: ["Deal, quote, invoice, and task management", "Integrated ticketing and service workflows", "Operations dashboards", "Marketing campaign tools", "Custom loyalty program management", "Call-center support integrations"],
    problem: "Disconnected sales, service, and marketing systems made customer journeys harder to manage and measure.",
    approach: "Created a component-driven frontend with RTK Query, robust forms, and AWS-ready deployment patterns for scalable business modules.",
    impact: "Improved operational visibility, customer satisfaction, and team productivity across connected business workflows.",
    live: "https://agenticcreed.ai/home",
    thumbnail: "/agentic-creed-main.jpg",
  },
  {
    slug: "compliance-sheet",
    title: "Compliance Sheet",
    summary: "A compliance management suite for inspections, learning, assurance, well-being, issues, and team communication.",
    description: "Compliance Sheet gives organizations a modern way to inspect sites, capture issues, assign tasks, train teams, and keep compliance work visible.",
    stack: ["React.js", "Next.js", "TypeScript", "RTK Query", "Redux Toolkit", "MUI", "Leaflet", "ApexCharts"],
    features: ["Real-time inspection capture", "Learning and development resources", "Well-being and safety modules", "Assurance and audit workflows", "Task and issue assignment", "Team communication tools"],
    problem: "Manual inspections and scattered compliance records made it difficult to catch risks early and coordinate action.",
    approach: "Built modular dashboards and workflows with real-time data handling, role-focused UI, maps, charts, and responsive layouts.",
    impact: "Improved issue visibility, sped up compliance actions, and helped teams keep training, assurance, and inspections aligned.",
    live: "https://compliancesheet.co.uk/",
    thumbnail: "/compliance-sheet-main.jpg",
  },
  {
    slug: "buzz-hr",
    title: "BuzzHr",
    summary: "An employee engagement platform for polls, surveys, feedback, workplace sentiment, and communication.",
    description: "BuzzHr helps organizations keep teams connected through lightweight feedback loops, real-time polls, and engagement dashboards.",
    stack: ["React.js", "Next.js", "TypeScript", "RTK Query", "Redux Toolkit", "MUI", "ApexCharts"],
    features: ["Real-time polls", "Employee surveys", "Direct communication channels", "Engagement insights", "Responsive interactive UI", "Feedback and sentiment tools"],
    problem: "Teams needed a better way to capture timely feedback and understand employee sentiment without slow manual surveys.",
    approach: "Built fast engagement flows, dashboard views, and reusable feedback components with RTK Query-backed state management.",
    impact: "Strengthened communication and gave teams clearer visibility into participation, mood, and engagement trends.",
    live: "https://buzzhr.peoplescreed.ai/dashboard",
    thumbnail: "/buzz-hr-main.jpg",
  },
  {
    slug: "clock-log",
    title: "ClockLog",
    summary: "A time, attendance, scheduling, reporting, and workforce productivity platform.",
    description: "ClockLog helps organizations track attendance, manage schedules, support payroll accuracy, and review productivity in real time.",
    stack: ["React.js", "Next.js", "TypeScript", "RTK Query", "Redux Toolkit", "ApexCharts", "MUI"],
    features: ["Time tracking", "Attendance and leave monitoring", "Real-time productivity reporting", "Shift scheduling tools", "Payroll-ready time logs", "Workforce insights"],
    problem: "Manual attendance and scheduling workflows created payroll errors, reporting delays, and weak accountability.",
    approach: "Created intuitive dashboards, automated logs, and reliable RTK Query data flows for attendance-heavy workflows.",
    impact: "Improved attendance accuracy, scheduling clarity, and workforce reporting speed.",
    live: "https://clocklog.peoplescreed.ai/dashboard",
    thumbnail: "/clock-log-main.jpg",
  },
  {
    slug: "share-my-dine",
    title: "Share My Dine",
    summary: "A social dining marketplace that connects home hosts and guests through authentic shared meals.",
    description: "Share My Dine turns home cooking into a community experience, helping hosts publish menus and guests discover meaningful dining moments.",
    stack: ["React.js", "TypeScript", "React Router", "Redux Toolkit", "Axios", "ECharts", "Formik", "MUI", "SASS"],
    features: ["Home meal hosting and bookings", "Host profiles, kitchens, and menus", "Scheduling and guest-host messaging", "Reviews and trust signals", "Role-based onboarding", "Responsive marketplace UI"],
    problem: "Traditional dining lacked the personal warmth, culture, and community connection of home-hosted meals.",
    approach: "Built scalable React screens with MUI, Redux Toolkit, Axios, and Formik, with attention to simple booking and hosting flows.",
    impact: "Helped hosts share food experiences while giving guests a more personal way to discover meals and communities.",
    live: "https://www.sharemydine.co.uk/",
    thumbnail: "/share-my-dine-main.jpg",
  },
  {
    slug: "foster-app",
    title: "FosterApp",
    summary: "A foster-care coordination platform for caregiver vetting, child profiles, placements, documents, and case tracking.",
    description: "FosterApp supports agencies and caregivers with structured workflows that make placement coordination clearer, safer, and easier to follow.",
    stack: ["React.js", "Next.js", "TypeScript", "RTK Query", "Redux Toolkit", "MUI", "TanStack Table", "ApexCharts"],
    features: ["Caregiver vetting workflows", "Secure child profile management", "Matching and placement coordination", "Case tracking and communication hub", "Financial and document management", "Dashboards, alerts, and analytics"],
    problem: "Foster placement processes were slowed by fragmented communication, documents, approvals, and case updates.",
    approach: "Built real-time dashboards, structured tables, alerts, and MUI-based workflows with TypeScript and RTK Query.",
    impact: "Reduced coordination delays and improved visibility between agencies and caregivers.",
    live: "https://fosterapp.co.uk/home",
    thumbnail: "/fosterapp-main.jpg",
  },
  {
    slug: "carer-library",
    title: "Carer Library",
    summary: "A learning-resource platform for growth, creativity, innovation, and organizational knowledge sharing.",
    description: "Carer Library centralizes curated learning content so organizations can encourage training, participation, and continuous improvement.",
    stack: ["React.js", "TypeScript", "RTK Query", "Ant Design"],
    features: ["Resource management", "Learning progress tracking", "Community engagement", "Curated content libraries"],
    problem: "Teams needed a single place to manage learning content and encourage ongoing skill development.",
    approach: "Built a React and TypeScript frontend with Ant Design components for content organization and learning workflows.",
    impact: "Made learning resources easier to discover, manage, and track.",
    live: "https://carer-library-project.vercel.app/login",
    thumbnail: "/care-library-main.jpg",
  },
  {
    slug: "soulencryption",
    title: "SoulEncryption",
    summary: "A secure digital vault for personal information, documents, relationships, wishes, assets, and life records.",
    description: "SoulEncryption helps users organize essential life information in one protected place so trusted people can access what matters when needed.",
    stack: ["React.js", "Next.js", "TypeScript", "React Hook Form", "MUI"],
    features: ["Personal, legal, health, and financial records", "Friends, family, nominees, and beneficiaries", "Property and asset organization", "Funeral planning and retirement records", "Digital asset storage", "Reminders, notes, and secure access controls"],
    problem: "Important personal documents are often scattered, inaccessible, or hard for loved ones to find during emergencies.",
    approach: "Designed modular, secure-feeling workflows with React Hook Form, MUI, and structured Next.js pages for sensitive life data.",
    impact: "Gave users and families a clearer, calmer way to store and access critical information.",
    live: "https://soule-encryption.vercel.app/home",
    thumbnail: "/soul-encryption-main.jpg",
  },
  {
    slug: "inowit",
    title: "Inowit",
    summary: "A digital marketing agency website for web design, SEO, content strategy, campaigns, and brand growth.",
    description: "Inowit presents marketing services through a modern, animated web experience built to explain offerings and drive client inquiries.",
    stack: ["React.js", "Next.js", "TypeScript", "Ant Design", "GSAP", "PostCSS", "Swiper"],
    features: ["Dynamic web design", "SEO service pages", "Digital campaigns", "Graphic design", "Email marketing", "Content strategy"],
    problem: "Small businesses needed a stronger web presence and a clearer service journey to turn visitors into customers.",
    approach: "Built a responsive Next.js experience with animated sections, service pages, Swiper interactions, and Ant Design UI patterns.",
    impact: "Improved service clarity, client engagement, and conversion-focused presentation.",
    live: "https://inowit.ca/home",
    thumbnail: "/inowit-main.jpg",
  },
  {
    slug: "smartsite",
    title: "SmartSite",
    summary: "A network and operations analytics platform for cost recovery, risk reduction, visualization, and automation.",
    description: "SmartSite helps enterprises understand complex networks, surface hidden costs, reduce risk, and automate operational analysis.",
    stack: ["React.js", "TypeScript", "Vite", "Tailwind CSS", "Radix UI", "React Google Maps", "Axios", "Postman"],
    features: ["Visualization dashboards", "Forensic analytics", "Cost reduction and recovery", "Risk reduction workflows", "Network optimization", "Operational efficiency tools"],
    problem: "Enterprise teams struggled with hidden spend, network risk, outdated inventory, and slow infrastructure decisions.",
    approach: "Built a fast Vite React frontend with accessible Radix UI patterns, maps, speech-enabled workflows, and API-backed analytics.",
    impact: "Helped clients gain clearer control over costs, vulnerabilities, inventories, and operational decisions.",
    live: "https://sitecert.nesterra.net/",
    thumbnail: "/cert-site-main.jpg",
  },
];

export function getProject(slug: string) {
  return projects.find((project) => project.slug.toLowerCase() === slug.toLowerCase());
}
